import PoliciesGrid from '../components/PoliciesGrid';
import CloseIcon from '@mui/icons-material/Close';
import IconButton from '@mui/material/IconButton';
import { Drawer, Box, Typography } from '@mui/material';

const PoliciesDrawer = ({ drawerOpen, setDrawerOpen, selectedAgent }) => {
  return (
    <Drawer anchor='right' open={drawerOpen} onClose={() => setDrawerOpen(false)}>
      <Box sx={{ p: 3, minWidth: 1200 }}>
        <Box display='flex' justifyContent='space-between' alignItems='center' mb={2}>
          <Typography variant='h6'>Policies for {selectedAgent?.name}</Typography>
          <IconButton onClick={() => setDrawerOpen(false)}>
            <CloseIcon />
          </IconButton>
        </Box>

        <PoliciesGrid
          agent={selectedAgent}
          agents={[]}
          policies={[
            {
              createdAtMs: 1705444800000,
              id: 'policy_123',
              agentIds: ['qUED8jhwwkfoVR84cXmdXTpgUON2'],
              beneficiaries: [
                {
                  firstName: 'Lesly',
                  lastName: 'Delaleu',
                  relationship: 'Spouse',
                  share: '100',
                },
              ],
              carrier: 'Corebridge',
              clientId: 'HekfqJxwEOX3dO7TOPW2',
              clientName: 'Josephine Delaleu',
              contingentBeneficiaries: [],
              coverageAmount: '10000',
              createdAt: '2026-01-16T12:00:00Z',
              dateSold: '2026-01-16',
              draftDay: '16',
              effectiveDate: '2026-01-16',
              leadSource: 'GetSeniorQuotes.com',
              notes: '',
              policyNumber: '7260013025',
              policyStatus: 'Active',
              policyType: 'SIWL',
              premiumAmount: '63.98',
              premiumFrequency: 'Monthly',
              source: 'WK | Trisha - Disaster | 01/10/2026',
              splitPolicy: false,
            },
            {
              createdAtMs: 1705531200000,
              id: 'policy_124',
              agentIds: ['qUED8jhwwkfoVR84cXmdXTpgUON2'],
              beneficiaries: [
                {
                  firstName: 'Michael',
                  lastName: 'Smith',
                  relationship: 'Child',
                  share: '100',
                },
              ],
              carrier: 'Mutual of Omaha',
              clientId: 'A1b2C3d4E5f6G7h8I9j0',
              clientName: 'Robert Smith',
              contingentBeneficiaries: [],
              coverageAmount: '25000',
              createdAt: '2026-01-17T10:30:00Z',
              dateSold: '2026-01-17',
              draftDay: '01',
              effectiveDate: '2026-02-01',
              leadSource: 'Facebook Ads',
              notes: 'Client requested early draft date.',
              policyNumber: 'MOO-998877',
              policyStatus: 'Pending',
              policyType: 'Whole Life',
              premiumAmount: '85.20',
              premiumFrequency: 'Monthly',
              source: 'FB Lead Gen | 01/12/2026',
              splitPolicy: false,
            },
            {
              createdAtMs: 1705617600000,
              id: 'policy_125',
              agentIds: ['qUED8jhwwkfoVR84cXmdXTpgUON2'],
              beneficiaries: [
                {
                  firstName: 'Sarah',
                  lastName: 'Connor',
                  relationship: 'Spouse',
                  share: '50',
                },
                {
                  firstName: 'John',
                  lastName: 'Connor',
                  relationship: 'Child',
                  share: '50',
                },
              ],
              carrier: 'Transamerica',
              clientId: 'Z9y8X7w6V5u4T3s2R1q0',
              clientName: 'Kyle Connor',
              contingentBeneficiaries: [],
              coverageAmount: '150000',
              createdAt: '2026-01-18T14:45:00Z',
              dateSold: '2026-01-18',
              draftDay: '18',
              effectiveDate: '2026-01-18',
              leadSource: 'Direct Mail',
              notes: '',
              policyNumber: 'TA-44556677',
              policyStatus: 'Active',
              policyType: 'Term',
              premiumAmount: '42.15',
              premiumFrequency: 'Monthly',
              source: 'DM Mailer #4 | 01/05/2026',
              splitPolicy: false,
            },
            {
              createdAtMs: 1705704000000,
              id: 'policy_126',
              agentIds: ['qUED8jhwwkfoVR84cXmdXTpgUON2', 'AGENT_B_556'],
              beneficiaries: [
                {
                  firstName: 'Elena',
                  lastName: 'Gilbert',
                  relationship: 'Sister',
                  share: '100',
                },
              ],
              carrier: 'Aetna',
              clientId: 'M1n2B3v4C5x6Z7l8K9j',
              clientName: 'Jeremy Gilbert',
              contingentBeneficiaries: [],
              coverageAmount: '5000',
              createdAt: '2026-01-19T09:15:00Z',
              dateSold: '2026-01-18',
              draftDay: '05',
              effectiveDate: '2026-02-05',
              leadSource: 'Warm Transfer',
              notes: 'Split policy with Agent B.',
              policyNumber: 'AET-102030',
              policyStatus: 'Active',
              policyType: 'Final Expense',
              premiumAmount: '35.00',
              premiumFrequency: 'Monthly',
              source: 'Call Center Transfer',
              splitPolicy: true,
            },
            {
              createdAtMs: 1705790400000,
              id: 'policy_127',
              agentIds: ['qUED8jhwwkfoVR84cXmdXTpgUON2'],
              beneficiaries: [
                {
                  firstName: 'Martha',
                  lastName: 'Wayne',
                  relationship: 'Spouse',
                  share: '100',
                },
              ],
              carrier: 'Americo',
              clientId: 'B1r2U3c4E5w6A7y8N9e',
              clientName: 'Thomas Wayne',
              contingentBeneficiaries: [],
              coverageAmount: '50000',
              createdAt: '2026-01-20T16:20:00Z',
              dateSold: '2026-01-20',
              draftDay: '20',
              effectiveDate: '2026-01-20',
              leadSource: 'GetSeniorQuotes.com',
              notes: 'Replacing old policy.',
              policyNumber: 'AMER-778899',
              policyStatus: 'Active',
              policyType: 'IUL',
              premiumAmount: '120.50',
              premiumFrequency: 'Monthly',
              source: 'WK | Trisha - Disaster | 01/15/2026',
              splitPolicy: false,
            },
            {
              createdAtMs: 1705876800000,
              id: 'policy_128',
              agentIds: ['qUED8jhwwkfoVR84cXmdXTpgUON2'],
              beneficiaries: [
                {
                  firstName: 'Linda',
                  lastName: 'Belcher',
                  relationship: 'Spouse',
                  share: '100',
                },
              ],
              carrier: 'Corebridge',
              clientId: 'B6o2B3s4B5u6R7g8E9r',
              clientName: 'Bob Belcher',
              contingentBeneficiaries: [],
              coverageAmount: '12000',
              createdAt: '2026-01-21T11:00:00Z',
              dateSold: '2026-01-21',
              draftDay: '21',
              effectiveDate: '2026-01-21',
              leadSource: 'Facebook Ads',
              notes: '',
              policyNumber: '7260014455',
              policyStatus: 'Active',
              policyType: 'SIWL',
              premiumAmount: '72.10',
              premiumFrequency: 'Monthly',
              source: 'FB Lead Gen | 01/18/2026',
              splitPolicy: false,
            },
            {
              createdAtMs: 1705963200000,
              id: 'policy_129',
              agentIds: ['qUED8jhwwkfoVR84cXmdXTpgUON2'],
              beneficiaries: [
                {
                  firstName: 'Jane',
                  lastName: 'Doe',
                  relationship: 'Daughter',
                  share: '100',
                },
              ],
              carrier: 'Mutual of Omaha',
              clientId: 'J1o2H3n4D5o6E7i8S9h',
              clientName: 'John Doe',
              contingentBeneficiaries: [],
              coverageAmount: '8000',
              createdAt: '2026-01-22T13:10:00Z',
              dateSold: '2026-01-22',
              draftDay: '03',
              effectiveDate: '2026-02-03',
              leadSource: 'Direct Mail',
              notes: '',
              policyNumber: 'MOO-112233',
              policyStatus: 'Lapsed',
              policyType: 'Final Expense',
              premiumAmount: '45.00',
              premiumFrequency: 'Monthly',
              source: 'DM Mailer #2 | 12/28/2025',
              splitPolicy: false,
            },
            {
              createdAtMs: 1706049600000,
              id: 'policy_130',
              agentIds: ['qUED8jhwwkfoVR84cXmdXTpgUON2'],
              beneficiaries: [
                {
                  firstName: 'Nancy',
                  lastName: 'Wheeler',
                  relationship: 'Mother',
                  share: '100',
                },
              ],
              carrier: 'Transamerica',
              clientId: 'M1i2K3e4W5h6E7e8L9e',
              clientName: 'Mike Wheeler',
              contingentBeneficiaries: [],
              coverageAmount: '250000',
              createdAt: '2026-01-23T15:50:00Z',
              dateSold: '2026-01-23',
              draftDay: '23',
              effectiveDate: '2026-01-23',
              leadSource: 'GetSeniorQuotes.com',
              notes: 'High coverage request.',
              policyNumber: 'TA-99001122',
              policyStatus: 'Active',
              policyType: 'Term',
              premiumAmount: '55.80',
              premiumFrequency: 'Monthly',
              source: 'WK | Trisha - Disaster | 01/20/2026',
              splitPolicy: false,
            },
            {
              createdAtMs: 1706136000000,
              id: 'policy_131',
              agentIds: ['qUED8jhwwkfoVR84cXmdXTpgUON2'],
              beneficiaries: [
                {
                  firstName: 'Gloria',
                  lastName: 'Pritchett',
                  relationship: 'Spouse',
                  share: '100',
                },
              ],
              carrier: 'Americo',
              clientId: 'J1a2Y3p4R5i6T7c8H9e',
              clientName: 'Jay Pritchett',
              contingentBeneficiaries: [],
              coverageAmount: '20000',
              createdAt: '2026-01-24T10:00:00Z',
              dateSold: '2026-01-24',
              draftDay: '24',
              effectiveDate: '2026-01-24',
              leadSource: 'Warm Transfer',
              notes: '',
              policyNumber: 'AMER-112244',
              policyStatus: 'Active',
              policyType: 'Whole Life',
              premiumAmount: '95.00',
              premiumFrequency: 'Monthly',
              source: 'Call Center Transfer',
              splitPolicy: false,
            },
            {
              createdAtMs: 1706222400000,
              id: 'policy_132',
              agentIds: ['qUED8jhwwkfoVR84cXmdXTpgUON2'],
              beneficiaries: [
                {
                  firstName: 'Lois',
                  lastName: 'Griffin',
                  relationship: 'Spouse',
                  share: '100',
                },
              ],
              carrier: 'Corebridge',
              clientId: 'P1e2T3e4R5g6R7i8F9f',
              clientName: 'Peter Griffin',
              contingentBeneficiaries: [],
              coverageAmount: '15000',
              createdAt: '2026-01-25T12:00:00Z',
              dateSold: '2026-01-25',
              draftDay: '25',
              effectiveDate: '2026-01-25',
              leadSource: 'Facebook Ads',
              notes: 'Nonsmoker rate.',
              policyNumber: '7260018899',
              policyStatus: 'Active',
              policyType: 'SIWL',
              premiumAmount: '88.45',
              premiumFrequency: 'Monthly',
              source: 'FB Lead Gen | 01/22/2026',
              splitPolicy: false,
            },
          ]}
          policiesLoading={false}
          agentsLoading={false}
          handleUpdatePolicy={() => {}}
          setPolicy={() => {}}
          setDeletePolicyOpen={() => {}}
        />
      </Box>
    </Drawer>
  );
};

export default PoliciesDrawer;
